### ISSUE TITLE
Saved state instance 1st Tab Auto Scroll issue

### ISSUE THREAD

**Issue by NandakumarB** [jpardogo/PagerSlidingTabStrip#101]
When restoring from saved state instance after selecting the first tab the tab automatically scrolls to another position and When again restoring from saved state instance it automatically scrolls to the original position

**Comment by jpardogo** [comment]
The sample works, review you code. Otherwise provide details of your implementation and why you identified it as a library issue.

**Comment by jpardogo** [comment]
@NandakumarB

**Comment by jpardogo** [comment]
@NandakumarB

**Comment by jpardogo** [comment]
I have been testing it and the tab position is working fine across rotation, there must be something wrong in the implementation.
