### ISSUE TITLE
Calling setOnPageChangeListener()

### ISSUE THREAD

**Issue by Wolftein** [jpardogo/PagerSlidingTabStrip#103]
Calling setOnPageChangeListener(...) will make the animation flickers for some reason; i currently have 3 Tabs (Ringtones, Notifications, Alarms), without calling setOnPageChangeListener the animation plays nice but when i use setOnPageChangeListener the animation starts flickering when moving

**Comment by Wolftein** [comment]
More precise when for example in onPageSelected(...) i set the toolbar title acording to the selected fragment.

**Comment by jpardogo** [comment]
I am gonna need the implementation details to see where the problem comes from. With the current information, it cannot be identify as a library issue.

**Comment by xxxifan** [comment]
Same here.

**Comment by xxxifan** [comment]
believe it or not, I set pstsTextSelectedStyle to normal, issue's gone
