### ISSUE TITLE
How to set Underline under Indicator 

### ISSUE THREAD

**Issue by NogerbekNurzhan** [jpardogo/PagerSlidingTabStrip#108]
Hello man Thanks for this wonderful project! I have 2 questions. I will try to explain it with pictures.

Thats what I want to make
![tabs0](https://cloud.githubusercontent.com/assets/8999232/7572813/caacfc38-f842-11e4-9b4b-a44eb3fb1490.png)

Thats what I have now
![picture_1](https://cloud.githubusercontent.com/assets/8999232/7572829/e3267988-f842-11e4-9a33-f91466151fd4.png)

My question. How to make as in first picture when  Underline under Indicator.

My second question is is it possible here to add shadows under the tabs?

**Comment by jpardogo** [comment]
Do not use the underline for this effect, use your own view (width="match_parent", height="X dp") under the MaterialPagerTabStrip with the background you want.

**Comment by NogerbekNurzhan** [comment]
@jpardogo Hello man! Thank you for your reply. I tried to make that effect with underline but it was unsuccessful. I tried to add View element inside Tabs but application crashed and I didnt find way how to fix it inside library. Can you show me right way to do that please!

**Comment by NogerbekNurzhan** [comment]
I tried somthing like that before which was unsuccesfull.

               <com.astuetz.PagerSlidingTabStrip
                            *custom settings here* >

                <View
                    android:layout_width="match_parent"
                    android:background="#FBC02D"
                    android:layout_height="5dp"/>
                
                </com.astuetz.PagerSlidingTabStrip>

**Comment by jpardogo** [comment]
Something like that.

```xml
<LinearLayout .... >
 <com.astuetz.PagerSlidingTabStrip .... />
    <View
        android:layout_width="match_parent"
        android:layout_height="5dp"
        android:background="#FBC02D"/>
</LinearLayout>
```

**Comment by NogerbekNurzhan** [comment]
@jpardogo Are you sure that it must be like that? I am not sure that it will be like in first picture. I think View element will be under PagerSlidingTabStrip but in my case I want to show it inside of PagerSlidingTabStrip. I tested it right now and as I expected View element under PagerSlidingTabStrip. Its like in the second picture of my post. View element here must be like underline but underline under Indicator line. I hope you understand me.
           <RelativeLayout
                 xmlns:android="http://schemas.android.com/apk/res/android"
                 xmlns:tools="http://schemas.android.com/tools"
                 xmlns:app="http://schemas.android.com/apk/res-auto"
                 android:layout_width="match_parent"
                 android:layout_height="match_parent">

            <include
                android:id="@+id/application_toolbar"
                layout="@layout/application_toolbar"/>

            <LinearLayout
                android:id="@+id/material_tabs"
                android:layout_width="match_parent"
                android:layout_height="56dp"
                android:orientation="vertical"
                android:layout_below="@+id/application_toolbar">

                <com.astuetz.PagerSlidingTabStrip 
                      android:layout_height="53dp"
                      ****/>

                <View
                    android:layout_width="match_parent"
                    android:layout_height="3dp"
                    android:background="#FBC02D"/>
            </LinearLayout>

            <android.support.v4.view.ViewPager
                android:id="@+id/pager"
                android:layout_below="@+id/material_tabs"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                tools:context=".MainActivity" />
        </RelativeLayout>

**Comment by NogerbekNurzhan** [comment]
I tested your updated code and result is the same as in the second picture. Do you have any ideas?!)

**Comment by jpardogo** [comment]
Yes sorry. That solved your second question for the shadow under the tabs.

For the first questions you have to take a look to #95 and #96. #96 was already merged in the dev branch for next release. So you will only need to set `pstsIndicatorHeightHeight ` and `pstsUnderlineHeight ` as you prefer.

**Comment by NogerbekNurzhan** [comment]
Thank you man! I didnt notice that this question was asked before. Thats exactly what I need. God bless you!
