### ISSUE TITLE
indicatorColor not working with pstsTabBackground ? 

### ISSUE THREAD

**Issue by sues-lee** [jpardogo/PagerSlidingTabStrip#109]
I tried to add touch effect (selector) for the tabs using:
`app:pstsTabBackground="@drawable/tab_selector"`
and it's working fine, but the indicator is not working. However, indicator working when I use `android:background` but I can't set touching effect using this approach.

**Comment by jpardogo** [comment]
`android:background ` is the tabs container color. 
`pstsTabBackground` is the individual tabs background.

It seems to work for me. Can you provider details of the problem with your implementation?

**Comment by sues-lee** [comment]
OK,this is my drawable resource,I wanna use the ripple effect in Lollipop:
`<ripple
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:color="@color/light_primary_color"
    >
    <item android:drawable="@color/back_ground_color" />
</ripple>`

My layout xml file:

        <com.astuetz.PagerSlidingTabStrip
                android:id="@+id/tab_strip"
                android:layout_width="match_parent"
                android:layout_height="@dimen/tab_bar_height"
                android:textColor="@color/secondary_text"
                android:background="@drawable/bg_tab_strip_white"
                app:pstsIndicatorHeight="2dp"
                app:pstsIndicatorColor="?attr/colorAccent"
                app:pstsShouldExpand="true"
                app:pstsTextColorSelected="?attr/colorPrimary"
                />
When I using `android:background` ,I got a no touch effect background:

![0d9734b3-ce53-40fe-ab8e-1e7bc07f2913](https://cloud.githubusercontent.com/assets/6863378/7645708/c557200a-faeb-11e4-9737-9e2daeaf17f3.png)

When I using `app:pstsTabBackground`,the indicator is not working but touch effect is working fine:

![4a5f7d9d-b70f-4f5e-916f-3635abd2531a](https://cloud.githubusercontent.com/assets/6863378/7645707/bab30ce0-faeb-11e4-9faf-c330c9746301.png)

**Comment by jpardogo** [comment]
You are using custom tabs. Use wrap content for `android:layout_height="wrap_content"` and the correct margin should be applied to the container of the tabs.

**Comment by jpardogo** [comment]
Done! Now I am applying padding to the `FrameLayout` parent of the tabsContainer and it gets applied correctly to custom tabs as well. It will be in for the next library update.

**Comment by sues-lee** [comment]
Thanks for the help
