### ISSUE TITLE
How to add a margin or padding to the left of the first tab?

### ISSUE THREAD

**Issue by subodh-malgonde** [jpardogo/PagerSlidingTabStrip#111]
I want to implement something like the below image. Notice the margin before the first tab starts:

![image](https://cloud.githubusercontent.com/assets/5463437/7726707/7dbe2182-ff21-11e4-8a9d-317da06c7770.png)

I went through the source code and the only option available to change the margin before the first tab is to set pstsPaddingMiddle="true". However since this keeps all the selected tabs at the center, the first tab appears at the center. Is there any other way to set some margin before the first tab?

**Comment by jpardogo** [comment]
On the README:

>android:paddingLeft or android:paddingRight layout padding. If you apply both, they should be balanced. PR #69 have a good explanation of this behaviour.

**Comment by subodh-malgonde** [comment]
Thanks.
