### ISSUE TITLE
Support Indicator Padding

### ISSUE THREAD

**Issue by jaredsburrows** [jpardogo/PagerSlidingTabStrip#113]
It would be nice to support `padding` on the sliding tab `indicator`. Here are a few examples.

## Google Example(Play Games App):
See the "Featured" tab [here](https://play.google.com/store/apps/details?id=com.google.android.play.games):
<img src="http://phandroid.s3.amazonaws.com/wp-content/uploads/2014/10/Google-Play-Games-Material-Design-update.jpg" />

## Non Google Example:
See the "Root" tab [here](https://play.google.com/store/apps/details?id=burrows.apps.rootchecker): 
<img src="https://lh5.ggpht.com/TSkGQ0hUTL4wzzhcq48rTsdOVAf8hLFPix4rAc66IOIedV7dU9WkcJkaDvPjIZ47J_8=h900" />

**Comment by jpardogo** [comment]
The library doesn't need to take care of every single user case. That's a problem for the maintenance and cleanliness of the code. This is easily achievable for each user wrapping the widget.

**Comment by jaredsburrows** [comment]
It is not really a "user case". A lot of the official Google android applications have the same type of padding on left and right, this and the material ripple is the only reason I have not switched to your repository yet. So is it not even worth making a pull request?

**Comment by jpardogo** [comment]
We are speaking about padding or ripples? You can wrap the layout to make it look like as you want. Even add PagerSlidingTabStrip inside the Toolbar.

**Comment by jaredsburrows** [comment]
`android:padding` is for the entire view. 

If you look at `RootChecker's` tabs, the sliding `indicator` has padding on either side just like Google Play and Google Play Games.

**Comment by jpardogo** [comment]
![screenshot_2015-05-26-18-15-46](https://cloud.githubusercontent.com/assets/1172221/7818485/ea14aee4-03d3-11e5-927d-3a2146e50b93.png)

Google play tab indicator doesn´t have padding. The tabs container does, on the left and right side.

**Comment by jaredsburrows** [comment]
@jpardogo I see, I can use `android:paddingLeft` and `android:paddingRight` and around the tabs inside of a `container`. Thanks for clearing that up.

**Comment by jaredsburrows** [comment]
Example:

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:paddingLeft="8dp"
        android:paddingStart="8dp"
        android:paddingRight="8dp"
        android:paddingEnd="8dp"
        android:background="?attr/colorPrimary"
        android:orientation="vertical">

        <com.astuetz.PagerSlidingTabStrip
            android:id="@+id/slidingTabs"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            android:foreground="?selectableItemBackground"
            android:textColor="#FFCCCCCC"
            tab:pstsShouldExpand="true"
            tab:pstsIndicatorColor="@android:color/white"
            tab:pstsTextColorSelected="@android:color/white" />
    </LinearLayout>

**Comment by jpardogo** [comment]
```xml 
<com.astuetz.PagerSlidingTabStrip
        android:id="@+id/slidingTabs"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:paddingLeft="8dp"
        android:paddingRight="8dp"
        android:background="?attr/colorPrimary"
        android:textColor="#FFCCCCCC"
        tab:pstsShouldExpand="true"
        tab:pstsIndicatorColor="@android:color/white"
        tab:pstsTextColorSelected="@android:color/white" />

<!-- android:foreground="?selectableItemBackground" is useless here -- >
```

**Comment by jaredsburrows** [comment]
Yes, I was just demonstrating your advice. I already have `PagerSlidingTabStrip` implemented in my apps + padding. Thanks again.

**Comment by shubhambansal** [comment]
@jpardogo : Is there a way to add padding for pstsIndicator? So the pstsIndicator exactly fits the tab textview width.
