### ISSUE TITLE
v 1.1.0 does not seem to available on Maven

### ISSUE THREAD

**Issue by vladp** [jpardogo/PagerSlidingTabStrip#116]
Hello
it looks like maven has only up to 1.0.9.

Also would appreciate if there could  an example that shows  using your library as an external dependency.

thank you in advance

**Comment by jpardogo** [comment]
Yes it is. Check the sample code. otherwise read gradle documentation to add dependencies.

http://gradleplease.appspot.com/#materialtabstrip

**Comment by bakua** [comment]
It is but it looks like it is missing PagerSlidingTabStrip class for some reason (or something else is broken). Because Android studio is not able to reference it.
