### ISSUE TITLE
Duplicate launcher icon

### ISSUE THREAD

**Issue by Nutomic** [jpardogo/PagerSlidingTabStrip#117]
After updating some dependencies in my project, I now get the following error:
```
app/build/intermediates/res/debug/drawable-xxhdpi/ic_launcher.png: error: Duplicate file.
app/build/intermediates/res/debug/drawable-xxhdpi-v4/ic_launcher.png: Original is here. The version qualifier may be implied.
```
According to [this post](http://stackoverflow.com/a/29977893), the library should not include a launcher icon, or at least use a prefix to avoid collisions. (The file is in `sample/res/drawable-*/ic_launcher.png`)

I'm not actually sure why this happens, as my `settings.gradle` only has `include ':PagerSlidingTabStrip:library'`.

Edit: As a workaround, I downgraded from `com.android.tools.build:gradle:1.2.3` to `com.android.tools.build:gradle:1.1.3`.

**Comment by jpardogo** [comment]
Sorry for the late reply. They problem is not the library I think the conflict is between your app ic_launcher and some other ic_launcher in one of your dependencies. The only package that the dependency include is the library which doesn't drawables but an xml one with prefix.
