### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by sergeyfitis** [jpardogo/PagerSlidingTabStrip#119]
Hi, your PagerSlidingTabStripis a good library. But it will be very nice if you implement next feature. When user scrolling tabs layout, during scroll viewpager must to be scrolled with the tabs and the tab's indicator will update its state too. Anyway, thank you.

**Comment by jpardogo** [comment]
Sorry but that that will not be a library feature, it is out of the scope of this library. Thanks for the request
