### ISSUE TITLE
Use PagerSlidingTabStrip no Eclipse

### ISSUE THREAD

**Issue by forewerton** [jpardogo/PagerSlidingTabStrip#121]
I was not able to import the PagerSlidingTabStrip from maven
http://search.maven.org/#artifactdetails%7Ccom.jpardogo.materialtabstrip%7Clibrary%7C1.0.9%7Caar

First Eclipse complain about the support-v4 which is no longer in Maven public repository
"Missing artifact com.android.support:support-v4:aar:21.0.3"

So I include the local repository in Android SDK extras following this steps
http://stackoverflow.com/questions/18380337/android-support-library-setup-with-maven

But after the dependences was solved I still get an error
"Missing artifact com.jpardogo.materialtabstrip:library:jar:1.0.9"

Any ideias!?

**Comment by jpardogo** [comment]
What can I say.... Do not use eclipse. I am not going to explain why you should android studio and gradle in here. Just do it.
