### ISSUE TITLE
not center vertical after upgrade to 1.1.0

### ISSUE THREAD

**Issue by xxxifan** [jpardogo/PagerSlidingTabStrip#122]
I've been use this library since 1.0.9, today I found it's updated and then I upgraded it.After I run new build on my phone I found the tab text is not center vertically.Is this a bug?I don't find a way to set it either

**Comment by jpardogo** [comment]
It works for me. The default tab is just a `TextView` with gravity center.

https://github.com/jpardogo/PagerSlidingTabStrip/blob/master/library/res/layout/psts_tab.xml#L7

If you send me more details I may be able to find the problem.
