### ISSUE TITLE
Full screen tab

### ISSUE THREAD

**Issue by crocoM4** [jpardogo/PagerSlidingTabStrip#126]
Hi,
i have a question.

if i have a menu with 3 tabs it look like the following screen

![screenshot_2015-07-22-16-53-50 1](https://cloud.githubusercontent.com/assets/13453791/8828833/676fb054-3094-11e5-8531-a776efe7b497.png)

but i want that the 3 tabs take the max width that they can have like the next screen

![screenshot_2015-07-22-17-06-49 1](https://cloud.githubusercontent.com/assets/13453791/8828901/aa030006-3094-11e5-8000-cb62f8d87846.png)

Who can i fix this? Thanks

ps: sorry for my bad english

**Comment by dsun29** [comment]
I am looking for the answer too.

**Comment by crocoM4** [comment]
It works. Thanks :)
