### ISSUE TITLE
Actionbar layout doesn't look right

### ISSUE THREAD

**Issue by trickydude** [jpardogo/PagerSlidingTabStrip#128]
I've gone through the steps to set up the tabs, however, my actionbar comes out looking like this:

[![enter image description here][1]][1]

Why is there an additional actionbar above the tabs? How do I fix this?

Here's my `activity_main.xml` layout:

    <RelativeLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context=".MainActivity">
    
        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/primary"
            android:minHeight="56dp"
            app:theme="@style/ThemeOverlay.AppCompat.Dark"/>
        
        <com.astuetz.PagerSlidingTabStrip
            android:id="@+id/tabs"
            android:layout_width="match_parent"
            android:layout_height="48dp"
            android:layout_below="@+id/toolbar"
            android:background="@color/primary"
            android:textColorPrimary="@color/white"
            app:pstsDividerColor="@color/primary"
            app:pstsIndicatorColor="@color/white"
            app:pstsIndicatorHeight="2dp"
            app:pstsShouldExpand="true"
            app:pstsUnderlineHeight="0dp"/>
    
        <android.support.v4.view.ViewPager
            android:id="@+id/pager"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_below="@+id/tabs"/>
    
    </RelativeLayout>

My `menu_main.xml` layout:

    <menu xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools" tools:context=".MainActivity">
        <item android:id="@+id/action_settings" android:title="@string/action_settings"
            android:orderInCategory="100" app:showAsAction="never" />
    </menu>

How do I fix this?

  [1]: http://i.stack.imgur.com/sFzer.png
  [2]: http://i.stack.imgur.com/rGPOW.gif

**Comment by jpardogo** [comment]
That´s because you are using the theme with the toolbar and adding another toolbar in the xml
