### ISSUE TITLE
Navigation bar color

### ISSUE THREAD

**Issue by TheLoyalCruel** [jpardogo/PagerSlidingTabStrip#131]
how to change navigation bar color by selecting colors?
thanks...

**Comment by crocoM4** [comment]
Use this:

PagerSlidingTabStrip tabs;

tabs = (PagerSlidingTabStrip) findViewById(R.id.tabs);

tabs.setBackgroundColor(R.color.yourColor);

**Comment by jpardogo** [comment]
Check sample app
