### ISSUE TITLE
How to make 2 tabs width fill parent?

### ISSUE THREAD

**Issue by AlexMercier** [jpardogo/PagerSlidingTabStrip#141]
I have 2 tabs. They gravity to left. but i want it to width fill parent and centered. How to make it?

![screen](http://i4.imageban.ru/out/2015/10/12/0c34b579e6c51d5b0b1182540b42e760.png)

**Comment by jpardogo** [comment]
It's written in the README please, read the readme. `pstsShouldExpand `
