### ISSUE TITLE
PagerSlidingTabStrip is not fit with Action Toolbar

### ISSUE THREAD

**Issue by heyou93** [jpardogo/PagerSlidingTabStrip#147]
The pabersliding tab strip is not really fit with Action Toolbar it looks like there is a shadow below the toolbar check the screenshot:

![12736560_1675160749403675_1627284593_o](https://cloud.githubusercontent.com/assets/8090574/13146119/2d18cb1a-d68f-11e5-929b-82924febbf93.jpg)

**Comment by jpardogo** [comment]
That has nothing to do with the library
