### ISSUE TITLE
When a tab gets selected its tabSelected() gets fired three times.

### ISSUE THREAD

**Issue by HeinrichReimer** [jpardogo/PagerSlidingTabStrip#148]
`tabSelected()` is fired three times when you select a tab and it's also fired when you slide away from the selected page. I think the problem here is that this code here is called in `onPageScrollStateChanged()` but it should be called in `onPageSelected()`.

````java
//Full tabTextAlpha for current item
View currentTab = mTabsContainer.getChildAt(mPager.getCurrentItem());
select(currentTab);
//Half transparent for prev item
if (mPager.getCurrentItem() - 1 >= 0) {
    View prevTab = mTabsContainer.getChildAt(mPager.getCurrentItem() - 1);
    unSelect(prevTab);
}

//Half transparent for next item
if (mPager.getCurrentItem() + 1 <= mPager.getAdapter().getCount() - 1) {
    View nextTab = mTabsContainer.getChildAt(mPager.getCurrentItem() + 1);
    unSelect(nextTab);
}

if (mDelegatePageListener != null) {
    mDelegatePageListener.onPageScrollStateChanged(state);
}
````
[*PagerSlidingTabStrip.java Line 447*](https://github.com/jpardogo/PagerSlidingTabStrip/blob/master/library/src/com/astuetz/PagerSlidingTabStrip.java#L447)

**Comment by jpardogo** [comment]
PR merge in dev branch for next release 6f2555686d38495cd4ef53c5bea7c549a9b0b0d6
