### ISSUE TITLE
How to capture click event on each tab?

### ISSUE THREAD

**Issue by ln206** [jpardogo/PagerSlidingTabStrip#152]
Hello,

I want to send an analytic event when user click on each tab. How do I listen to these events? Please let me know, thanks.

**Comment by jpardogo** [comment]
From README.md :

"5.(Optional) If you use an OnPageChangeListener with your view pager you should set it in the widget rather than on the pager directly.

   // continued from above
   `tabs.setOnPageChangeListener(mPageChangeListener);`"
