### ISSUE TITLE
Problem maintaining tab highlight upon orientation change

### ISSUE THREAD

**Issue by MizzleDK** [jpardogo/PagerSlidingTabStrip#33]
I'm experiencing a slightly strange issue, and for whatever reason it only occurs on my Nexus 5, but not on my Nexus 9. It's kind of hard to describe, so I'll start with some screenshots.

This is what the application looks like to begin with:

![device-2014-12-01-001835](https://cloud.githubusercontent.com/assets/1175953/5239834/4b9a48f0-78f0-11e4-8e96-44e2b64c3097.jpg)

As you can see, there are a number of tabs, starting with "All movies", "Favorites" and "New releases". Whenever I swipe to a tab that's not the first tab, it messes up the highlighting upon orientation change.

Here's an example, starting with the "New releases" tab selected:

![device-2014-12-01-001919](https://cloud.githubusercontent.com/assets/1175953/5239844/8cccb786-78f0-11e4-8769-cf05e4ae466a.jpg)

Rotate the device, and this is what it looks like:

![device-2014-12-01-001944](https://cloud.githubusercontent.com/assets/1175953/5239846/a3a528a8-78f0-11e4-89b1-fe193664e464.jpg)

As you can see, it doesn't look right. Here's a screenshot of what it looks like when I scroll the tabs a bit:

![device-2014-12-01-001956](https://cloud.githubusercontent.com/assets/1175953/5239850/c5faa626-78f0-11e4-9644-cd87ba520362.jpg)

Once I start scrolling the actual content, it fixes itself immediately:

![device-2014-12-01-002006](https://cloud.githubusercontent.com/assets/1175953/5239851/d291c1da-78f0-11e4-910e-2db30557bd3b.jpg)

**Comment by sockeqwe** [comment]
It also seems that the correct tab is highlighted if I jump to a certain page in the `ViewPager.setCurrentItem(int position)` from`Activities.onCreate()` ... Maybe a simple fix would be to add a `OnPredrawDrawListener` and set the highlighted Tab by using `ViewPager.getCurrentItem()`

**Comment by jpardogo** [comment]
Fix on PR #51
