### ISSUE TITLE
The tabs do not scale correctly when using pstsShouldExpand="true" when rotating the device

### ISSUE THREAD

**Issue by Genxbit** [jpardogo/PagerSlidingTabStrip#34]
Hi,

first of all, a really great project!

if I use pstsShouldExpand="true" with two tabs and rotate my Nexus 7 from portrait to landscape and then back again, then the tabs still have the width from the landscape layout, i.e the first tab covers most of the width in portrait.

it worked correctly in v1.0.5 and the changed behavior was in the commit: "Fix tabsContainer always have to be as wide as the parent".

if i revert the following lines back in that commit:

From:
     @Override
     protected void onLayout(boolean changed, int l, int t, int r, int b) {
        //Make sure tabContainer is bigger than the HorizontalScrollView to be able to scroll
        tabsContainer.setMinimumWidth(getWidth());
        //Clipping padding to false to see the tabs while we pass them swiping
        setClipToPadding(false);

To:
     @Override
     protected void onLayout(boolean changed, int l, int t, int r, int b) {
       if (isPaddingMiddle) {
           //Make sure tabContainer is bigger than the HorizontalScrollView to be able to scroll
           tabsContainer.setMinimumWidth(getWidth());
           //Clipping padding to false to see the tabs while we pass them swiping
           setClipToPadding(false);
       }

i.e. add the condition back with isPaddingMiddle then that tabs works correctly with pstsShouldExpand="true".

Regards/
Lars

**Comment by jcady92** [comment]
Can you update Maven with the new version?

**Comment by MizzleDK** [comment]
An update release would be nice :+1:
