### ISSUE TITLE
underline changes position, but white text not change position

### ISSUE THREAD

**Issue by almaz010891** [jpardogo/PagerSlidingTabStrip#40]
When    mViewPager.setCurrentItem(position) underline changes position, but white text not change position
screenshot here: http://hkar.ru/x5vd
Sorry for my English.

**Comment by jpardogo** [comment]
If it is the case I will close this issue and I think I will close issue #33 as well. Everyone agree?

**Comment by jpardogo** [comment]
Fix on PR #51
