### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by VitalikL** [jpardogo/PagerSlidingTabStrip#47]
For some reason this implementation is very very laggy in comparison with original astuetz/PagerSlidingTabStrip. Following setup will reproduce the issue:

1. Main activity layout is DrawerLayout with Fragments being loaded to the ViewPager's manager
2. Add more than 5 pages to the pager
3. Each fragment has ScrollView as the root element and couple more views inside (ex. create a simple View with 500dp height)

Swiping and scrolling loses frames, which is not the case when using original lib.

**Comment by jpardogo** [comment]
Can you explain and report in detail the performance issues you have? Does anybody else have performance issues with this library?

**Comment by xDragonZ** [comment]
@VitalikL What happen if you add this? `mPager.setOffscreenPageLimit(3);`

http://stackoverflow.com/questions/21322207/how-does-setoffscreenpagelimit-improve-viewpager-performance-by-retaining-more

**Comment by r0adkll** [comment]
I too am having performance issues with this library. I have set `.setOffscreenPageLimit(3);` to no avail.

**Comment by Kev1000000** [comment]
I am also having performance issues.  It seems the GPU is doing a lot in the "process" (orange) step during profiling with this view added to the hierarchy.  When you take it out, that large "process" time goes away.

**Comment by VitalikL** [comment]
@xDragonZ Tried with this setting as well. Does not do anything different.

**Comment by jpardogo** [comment]
[This](https://twitter.com/romainguy/status/557720242802397186) could be  the problem....

**Comment by Kev1000000** [comment]
Nice find!  Just so you're aware, this is the result of the GPU profiler, with just the tabs enabled.  Something is definitely pegging the GPU hard.

http://i.imgur.com/MZ1j8BN.png

**Comment by yolapop** [comment]
I'm having issue with this too.. what is the solution?

**Comment by Kev1000000** [comment]
Are you planning on fixing this, or should we look for a separate lib?

**Comment by yolapop** [comment]
@Kev1000000 you can actually fix this yourself, just remove the `View.setAlpha` method and set the color. (as I did in here, https://github.com/yolapop/PagerSlidingTabStrip - i forgot if I added an text color attribute or not, but I could set inactive text color with ARGB color)

**Comment by csbenz** [comment]
@yolapop Thanks for making the code modifications! Could you make a pull request so @jpardogo can merge with this library?

**Comment by yolapop** [comment]
Hi sorry for the delay, I just created a PR. https://github.com/jpardogo/PagerSlidingTabStrip/pull/66
