### ISSUE TITLE
View does not use its own textColorPrimary value

### ISSUE THREAD

**Issue by elliottsj** [jpardogo/PagerSlidingTabStrip#48]
If I specify the `textColorPrimary` as an attribute of the view (or if I specify it in a theme via the `style` attribute), the value is ignored and `textColorPrimary` from the parent theme is used instead.

```xml
<com.astuetz.PagerSlidingTabStrip
        android:id="@+id/tabs"
        android:layout_width="match_parent"
        android:layout_height="?android:actionBarSize"
        android:textColorPrimary="@android:color/white"
        app:pstsShouldExpand="true" />
```
(i.e. the `@android:color/white` value is ignored)

I've tried breaking on this line ([PagerSlidingTabStrip.java#L156](https://github.com/jpardogo/PagerSlidingTabStrip/blob/v1.0.6/library/src/com/astuetz/PagerSlidingTabStrip.java#L156)) to see if `obtainStyledAttributes` is returning the right attributes:

While paused, running the expression
```java
context.obtainStyledAttributes(attrs, new int[] {android.R.attr.textColorPrimary}).getString(0)
```
gives me the correct value of `"#ffffffff"`. But running
```java
context.obtainStyledAttributes(attrs, ATTRS).getString(TEXT_COLOR_PRIMARY)
```
gives me the incorrect value of `"#ff212121"` (from the parent theme).

Then, stepping past [L#159](https://github.com/jpardogo/PagerSlidingTabStrip/blob/v1.0.6/library/src/com/astuetz/PagerSlidingTabStrip.java#L159), `int textPrimaryColor` has that same incorrect value (converted to an int): `-14606047` (`== 0xFF212121`)

---

I'm wondering if this is an Android issue because
```java
context.obtainStyledAttributes(attrs, new int[] {android.R.attr.textColorPrimary}).getString(0)
```
should really be the same value as
```java
context.obtainStyledAttributes(attrs, ATTRS).getString(TEXT_COLOR_PRIMARY)
```

**Comment by jpardogo** [comment]
Why do you use `android:textColorPrimary="@android:color/white"` ? this attr doesn't exist. You should use `android:textColor="@android:color/white"`

**Comment by elliottsj** [comment]
`android:textColorPrimary` is defined in the app theme, so I thought you should be able to override theme attributes like this on a view-by-view basis.

```xml
<com.astuetz.PagerSlidingTabStrip
        android:id="@+id/tabs"
        android:layout_width="match_parent"
        android:layout_height="?android:actionBarSize"
        android:textColorPrimary="@android:color/white"
        app:pstsShouldExpand="true" />
```

Should be equivalent to

```xml
<com.astuetz.PagerSlidingTabStrip
        style="@style/TabStrip"
        android:id="@+id/tabs"
        android:layout_width="match_parent"
        android:layout_height="?android:actionBarSize"
        app:pstsShouldExpand="true" />
```
```xml
<!-- res/values/styles.xml -->
...
<style name="TabStrip">
    <item name="android:textColorPrimary">@android:color/white</item>
</style>
...
```

**Comment by jpardogo** [comment]
Sorry I got confuse, yes we need `android.R.attr.textColor` and  `android.R.attr.textColorPrimary` 
https://github.com/jpardogo/PagerSlidingTabStrip/blob/master/library/src/com/astuetz/PagerSlidingTabStrip.java#L163
