### ISSUE TITLE
java.lang.NoSuchFieldError: com.astuetz.pagerslidingtabstrip.R$id.tab_title

### ISSUE THREAD

**Issue by younes0** [jpardogo/PagerSlidingTabStrip#59]
could you please explain to me this error? This doesn't happen when I add an textView with tab_title id, docs don't mention to add it although, and still I get other issue, the view is blank... 
```java
java.lang.NoSuchFieldError: com.astuetz.pagerslidingtabstrip.R$id.tab_title
            at com.astuetz.PagerSlidingTabStrip.addTab(PagerSlidingTabStrip.java:279)
            at com.astuetz.PagerSlidingTabStrip.notifyDataSetChanged(PagerSlidingTabStrip.java:253)
            at com.astuetz.PagerSlidingTabStrip.setViewPager(PagerSlidingTabStrip.java:236)
```

**Comment by jpardogo** [comment]
What is your layout file? I think that [this](http://stackoverflow.com/a/16674125/1787135) is what is happening

**Comment by younes0** [comment]
Thanks for your response

this is my tabs fragment layout:
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <TextView android:layout_width="match_parent" android:layout_height="match_parent"
            android:id="@+id/tab_title"/>
    <com.astuetz.PagerSlidingTabStrip
            android:id="@+id/tabs"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary" />

    <android.support.v4.view.ViewPager
            android:id="@+id/viewpager"
            android:layout_width="match_parent"
            android:layout_height="0px"
            android:layout_weight="1"
            android:background="@android:color/white"/>
</LinearLayout>
```

And this is the tab fragment:
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <ListView
        android:id="@+id/list"
        android:choiceMode="multipleChoice"
        android:dividerHeight="1dp"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

</LinearLayout>
```

**Comment by jpardogo** [comment]
Why is this TextView over the `PagerSlidingTabStrip` view?

**Comment by younes0** [comment]
Sorry that was for testing purposes.
When I'm adding that TextView, it doesn't produce the mentionned error. 

This is what I get when I put the TextView below
![untitled](https://cloud.githubusercontent.com/assets/886042/5915128/088f19b6-a602-11e4-9ab6-ddeeeb208de7.png)
Tab / Fragment switching works but tab title isn't shown as you can see you (no problem related to the adapter as it returns title)

**Comment by jpardogo** [comment]
What is the name of the layout of your custom tab?

**Comment by younes0** [comment]
I don't have any custom tab, it is required?

**Comment by jpardogo** [comment]
No, but I thought it was the feature you were using. Can you explain into detail what you are doing? It seems to be a problem in your code.

**Comment by younes0** [comment]
```java
public class FilterFragment extends Fragment {

    protected ViewPager pager;
    protected MaterialTabHost tabHost;
    protected MyPagerAdapter adapter;

    @Override public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_filter_tabs, container, false);
        ButterKnife.inject(this, view);

        // Initialize the ViewPager and set an adapter
        ViewPager pager = (ViewPager) view.findViewById(R.id.viewpager);
        pager.setAdapter(new MyPagerAdapter(getActivity().getSupportFragmentManager()));

        // Bind the tabs to the ViewPager
        PagerSlidingTabStrip tabs = (PagerSlidingTabStrip) view.findViewById(R.id.tabs);
        tabs.setViewPager(pager);

        return view;
    }

    public class MyPagerAdapter extends FragmentPagerAdapter {

        private final String[] TITLES = {"Categories", "Home" };

        public MyPagerAdapter(FragmentManager fm) {
            super(fm);
        }

        @Override
        public CharSequence getPageTitle(int position) {
            return "hello";
        }

        @Override
        public int getCount() {
            return 2;
        }

        @Override
        public Fragment getItem(int position) {
             return new FilterOriginsFragment();
        }
    }
}

public class FilterOriginsFragment extends Fragment {

    public FilterOriginsFragment() {}

    protected View mView;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        mView = inflater.inflate(R.layout.fragment_filter_origins, container, false);
        setHasOptionsMenu(true);
/* .. */
        return mView;
    }
}
```

**Comment by jpardogo** [comment]
You have 2 fragments but just 1 Title?

**Comment by younes0** [comment]
@jpardogo this is for debugging purposes

**Comment by jpardogo** [comment]
You should have same number of titles and fragments. Try like that and then check if anything is still happening

**Comment by jpardogo** [comment]
You are not getting hello hello? when does it crash?

**Comment by jpardogo** [comment]
Are you using gradle? Or you added the library yourself as a library project?

**Comment by younes0** [comment]
It crashes as I instanciate the fragment with a custom navigation drawer (neokree)
The image you saw is when I add 
```xml
  <TextView android:layout_width="match_parent" android:layout_height="match_parent"
            android:id="@+id/tab_title"/>
```
Which I don't want since I'm fine with the default tab layout..

I'm using gradle

**Comment by jpardogo** [comment]
You are using a ViewPager with fragments inside a fragment:

1.I would not complicate that much the app architecture, unless it is strictly necessary.
2. I you still want to do it this get , you should pass `getChildFragmentManager()` instead of `getActivity().getSupportFragmentManager()`

I am not sure that it is the problem but at least , worth to mention

**Comment by younes0** [comment]
1. problem is, I'm using a custom navigation drawer which works with fragments
2. unfortunately, that didn't work, getting the same error & crash.

Thanks for your help...

**Comment by jpardogo** [comment]
Do you have any layout in your project called tab.xml?

**Comment by jpardogo** [comment]
"If you have one project working as a library that declares some id in a given XML file, then your main project redefines that XML, the original id is gone, but you won't see the error until run time."

**Comment by younes0** [comment]
I have checked that SO question: I don't have any `tab.xml` or any duplicate xml filename file or any ressource called `tab_title`

**Comment by younes0** [comment]
wait... now I'm doubtful, I still have that other similar library in gradle. Keep you informed in 5 min

**Comment by jpardogo** [comment]
I have actually implemented the ViewPager inside a fragment last week for the same reason you are doing it. And It worked fine... I am really curious about this error.... Don't you see any difference between the example code and yours? Did you try to create a fresh new project and implement a simplify example to see what could be happening and find the error?

**Comment by jpardogo** [comment]
If you have more libraries about tabs it could be that 2 of the resources are being overwriten. Two tab.xml layouts.

**Comment by jpardogo** [comment]
That's the problem:

https://github.com/neokree/MaterialTabs/blob/master/MaterialTabsModule/src/main/res/layout/tab.xml

**Comment by younes0** [comment]
okay, so the problem was that I had also  'it.neokree:MaterialTabs:0.11' which uses the same XML ids.
May I suggest you to namespace the XML ids

**Comment by younes0** [comment]
Thank you so much for your time
