### ISSUE TITLE
Incorrect indicator positioning on custom fragment width

### ISSUE THREAD

**Issue by adiksonline** [jpardogo/PagerSlidingTabStrip#61]
I'm overriding the FragmentAdapter#getPageWidth (for tablets) in my app.
It looks like because the last tab is smaller than the full device width (thereby not starting from the farthest left), the indicator assumes the pager is still in transit and remains at a few pixels before its actual destination.

I've reproduced this in the sample by overriding `getPageWidth` in `MyPagerAdapter`
```java
public class MyPagerAdapter extends FragmentPagerAdapter {

        // . . .

        @Override
        public float getPageWidth(int position) {
            return 0.7F;
        }
    }
```

OUTPUT
This is correct
![screenshot_2015-01-26-10-43-04](https://cloud.githubusercontent.com/assets/1633684/5898130/99f2b75c-a54c-11e4-995a-13612f76450a.png)

Last tab - indicator doesn't reach its final destination
![screenshot_2015-01-26-10-43-12](https://cloud.githubusercontent.com/assets/1633684/5898131/99f9efe0-a54c-11e4-88b7-183bbabdab38.png)

**Comment by ataulm** [comment]
:+1: this is because the rect representing the indicator is calculated assuming that `currentPositionOffset == 0` is true when not travelling between tabs.

>`public abstract void onPageScrolled (int position, float positionOffset, int positionOffsetPixels)`
>
>This method will be invoked when the current page is scrolled, either as part of a programmatically initiated smooth scroll or a user initiated touch scroll.
>
> Parameters
> _position_	Position index of the first page currently being displayed. Page position+1 will be visible if positionOffset is nonzero.
> _positionOffset_	Value from [0, 1) indicating the offset from the page at position.
> _positionOffsetPixels_	Value in pixels indicating the offset from position.

**Comment by jpardogo** [comment]
I am now working in another issues but you can go for this approach to show both pages on the sides. I will check asap the `getPageWidth ` approach.

```xml
        <android.support.v4.view.ViewPager
            android:id="@+id/pager"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:paddingRight="50dp"
            android:paddingLeft="50dp"
            android:clipToPadding="false"
            tools:context=".MainActivity"/>
```

**Comment by jpardogo** [comment]
Use the approach above

**Comment by adiksonline** [comment]
Ah. Yes
The approach you suggested won't work for the case where only a select few of the pages need to be given a specific width though?

**Comment by jpardogo** [comment]
The library won´t be able to handle every user case. For special cases like this one. People can fork or implement his own tabs.
