### ISSUE TITLE
How to remove line between Toolbar and TabStrip?

### ISSUE THREAD

**Issue by squeeish** [jpardogo/PagerSlidingTabStrip#62]
![Image]
(http://i.imgur.com/xIbBrCo.png)

How do I remove the grey shadow/line as shown above?

My layout is as follows:

`<android.support.v7.widget.Toolbar
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:theme="@style/ThemeOverlay.AppCompat.ActionBar"
        android:background="?attr/colorPrimaryDark"/>`

`<com.astuetz.PagerSlidingTabStrip
android:id="@+id/tabs"
android:layout_width="match_parent"
android:layout_height="40dp"
android:elevation="4dp"
android:background="?attr/colorPrimary"
android:textColor="@color/white"
app:pstsIndicatorColor="@color/white"
app:pstsShouldExpand="true"
/>`

**Comment by IGZJcMinarro** [comment]
You have to set the same "elevation" that the toolbar.
To do that add the next attribute to you PSTS:

```xml

<com.astuetz.PagerSlidingTabStrip 
                .......
		android:elevation="4dp"
                .......
/>
```

**Comment by squeeish** [comment]
Hi @IGZJcMinarro, the elevation attribute is already defined though. 

Might it be related to way I inflate my layouts?

The toolbar is defined in activity_main.xml which is inflated in MainActivity.java. Fragments are then inserted in by navigation drawer. I do not use `<include layout.../>` like done in the sample app.

**Comment by jpardogo** [comment]
You mean the white one line? or the shadow?
