### ISSUE TITLE
BUG after Tabs.setTypeface in API 10 

### ISSUE THREAD

**Issue by FreakMurderer** [jpardogo/PagerSlidingTabStrip#77]
I understand - this API very old, but.... 

after `Tabs.setTypeface` command - tabs indicator not moving during Pager is scrolled... 
For example : `mTabs.setTypeface(Typeface.createFromAsset(getAssets(), "fonts/Roboto-Medium.ttf"), Typeface.NORMAL);`

P.S. How set the same typeface in XML ?

**Comment by jpardogo** [comment]
For now you can use customTabs with a CustomTextView that display the typeface you want.
I will take a look into this soon.

**Comment by FreakMurderer** [comment]
Please, give example ...

**Comment by jpardogo** [comment]
#82 is related with this issue

**Comment by jpardogo** [comment]
Please send you implementation to see what is the error

**Comment by jpardogo** [comment]
@FreakMurderer

**Comment by jpardogo** [comment]
I have just check in API 10 and works fine. 

```java
        pager.setAdapter(adapter);
        tabs.setTypeface(Typeface.createFromAsset(getAssets(), "Roboto-Light.ttf"), Typeface.NORMAL, Typeface.NORMAL);
        tabs.setViewPager(pager);
```

In the next release there will be a new `setTypeface` method to set custom fonts. The other have been deprecated.

```java
    @Deprecated
    public void setTypeface(Typeface typeface, int style)

    setTypeface(Typeface typeface, int style, int selectedStyle)
```
