### ISSUE TITLE
no background

### ISSUE THREAD

**Issue by hamutarto** [jpardogo/PagerSlidingTabStrip#81]
Hey!

When I'd like to set the background of the tab strip with the following way:

            <com.astuetz.PagerSlidingTabStrip
                android:id="@+id/tabs"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:background="?attr/colorPrimary"
                app:pstsIndicatorColor="@color/tab_indicator_color"
                />

it remains transparent, however the primary color is green.

Do you know what I'm doing wrong? The setbackground function is also useless.

Cheers,
Gabor

**Comment by squeeish** [comment]
It works for me. Try defining your colour in colors.xml and assign that instead?

    android:background="@color/my_primary_color"

**Comment by jpardogo** [comment]
The sample code works this way.... Could you provide your implementation to see what is the problem?

**Comment by jpardogo** [comment]
I think this is not a library issue but a misconfiguration in your project because the sample code works with  `android:background="?attr/colorPrimary"` https://github.com/jpardogo/PagerSlidingTabStrip/blob/master/sample/res/layout/activity_main.xml#L15
