### ISSUE TITLE
Ability to disabled indicator , Divider? 

### ISSUE THREAD

**Issue by soapsign** [jpardogo/PagerSlidingTabStrip#83]
Can I disable drawing these components completely?
I know I can hide them by setting color to transparent, but it seems inefficient.

**Comment by jpardogo** [comment]
Good point I will take a look and if it doesn't overcomplicate the current api and implementation I will do it.

**Comment by jpardogo** [comment]
Same thing for indicator and underline I guess...

**Comment by jpardogo** [comment]
So far:
* The divider won't be draw unless `dividerWidth` is specified in as bigger than 0. Default value is 0. https://github.com/jpardogo/PagerSlidingTabStrip/blob/master/library/src/com/astuetz/PagerSlidingTabStrip.java#L419

I am gonna take a look to do the same for underline and indicator.
