### ISSUE TITLE
how to divide titles across the screen

### ISSUE THREAD

**Issue by anoop-coolest** [jpardogo/PagerSlidingTabStrip#85]
I am using only two items as title. And it produces the follwing view
![screenshot_2015-03-12-20-41-28 1](https://cloud.githubusercontent.com/assets/7270504/6620795/b6386c16-c8f8-11e4-8fa0-1db0c6d22417.png)
But what i want to do is to divide those two titles across the entire toolbar.
How to achieve this?

**Comment by jpardogo** [comment]
It doesn't work or you just didn't read the README file?

README says: `pstsShouldExpand` If set to true, each tab is given the same weight, default false.

**Comment by anoop-coolest** [comment]
I tried but i get the same result.
here is the code i used:
tabs.setShouldExpand(true);
Is there anything else i should do?

**Comment by jpardogo** [comment]
I don't know at what point in the code you are actually doing the call. Anyway, why don't you just define it on the xml. 'app:pstsShouldExpand="true"'

**Comment by anoop-coolest** [comment]
Thanks...that xml worked

**Comment by gonzaloaune** [comment]
I can confirm the XML solution worked but on runtime, the setShouldExpand(true) doesn't. If I have time I will fix it during the weekend.

**Comment by DenisMondon** [comment]
Hi
Did you fix the setShouldExpand issue?

Thanks :)
