### ISSUE TITLE
initial pager position issue

### ISSUE THREAD

**Issue by szuwest** [jpardogo/PagerSlidingTabStrip#88]
If I want the initial pager position not 0, let it be the last page of position, and the view is showing not correctly. For example, add setCurrentItem(adapter.getCount()-1) to the last of onCreate method of the MainActivity. You will understand what I say. Anybody can help fix this? I try, but I failed. Thanks in advance.

**Comment by jpardogo** [comment]
The sample starts in the first position. Check the sample.
