### ISSUE TITLE
Alpha on non-selected custom tabs

### ISSUE THREAD

**Issue by nwhessel** [jpardogo/PagerSlidingTabStrip#90]
Is there any way to apply alpha to non-selected tabs when they are custom like it is with text tabs?

**Comment by yolapop** [comment]
I can apply alpha to non selected tabs using `android:textColor="#80FFFFFF"` or `pstsTextAlpha`. If you use `pstsTextAlpha`, the color of non selected tabs will be taken from `android:textColorPrimary`

**Comment by nwhessel** [comment]
Yes this works for the default text tabs. My question is how to do the same with custom tabs (such as icon tabs).

**Comment by efecannn** [comment]
Example:

tabs = (PagerSlidingTabStrip) findViewById(R.id.pagerSlidingTabStrip);
        pager = (ViewPager) findViewById(R.id.viewPager);
        adapter = new ContactPagerAdapter(getSupportFragmentManager(),this);
        pager.setAdapter(adapter);
        tabs.setViewPager(pager);
        tabs.setOnPageChangeListener(adapter);

Adapter:

public static class ContactPagerAdapter extends FragmentPagerAdapter implements PagerSlidingTabStrip.CustomTabProvider, ViewPager.OnPageChangeListener {

        private final int[] ICONS = {
                R.mipmap.ic_tab_x1_24dp,
                R.mipmap.ic_tab_x2_24dp,
                R.mipmap.ic_chat_x3_24dp};

        private final Fragment[] FRAGMENTS = {
                new F1(),
                new F2(),
                new F3()};

        private List<ImageView> tab_icon_list = new ArrayList<>();

        private final Context mContext;

        public ContactPagerAdapter(FragmentManager fm, Context context) {
            super(fm);
            mContext = context;
        }

        @Override
        public View getCustomTabView(ViewGroup parent, int position) {
            LinearLayout Layout = (LinearLayout) LayoutInflater.from(mContext).inflate(R.layout.main_tab_image_view, parent, false);
            ImageView im = ((ImageView)Layout.findViewById(R.id.image));
            im.setImageResource(ICONS[position]);
            tab_icon_list.add(im);

            return Layout;
        }

        @Override
        public int getCount() {
            return ICONS.length;
        }

        @Override
        public Fragment getItem(int position) {
            return FRAGMENTS[position];
        }

        @Override
        public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {

        }

        @Override
        public void onPageSelected(int position) {
            int i = 0;
            for (ImageView im : tab_icon_list) {
                if(position == i) {
                    im.setAlpha(255);
                } else {
                    im.setAlpha(200);
                }

                i++;
            }
        }

        @Override
        public void onPageScrollStateChanged(int state) {

        }
    }

**Comment by nwhessel** [comment]
Awesome! Thank you
