### ISSUE TITLE
Tabs wrong height in landscape

### ISSUE THREAD

**Issue by nwhessel** [jpardogo/PagerSlidingTabStrip#91]
When in lanscape the tabs height doesn't match the toolbar height at 56dp. They are instead only 48dp tall. This causes the current tab indicator to hover 4dp above the bottom of the toolbar.

![screenshot_2015-03-27-18-09-46](https://cloud.githubusercontent.com/assets/9904661/6878470/b2541806-d4ac-11e4-9fce-015bb38b5be5.png)
![screenshot_2015-03-27-18-10-02](https://cloud.githubusercontent.com/assets/9904661/6878469/b2523de2-d4ac-11e4-912c-00a0f052a63b.png)

**Comment by jpardogo** [comment]
```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.Toolbar xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/toolbar"
    android:layout_width="match_parent"
    android:layout_height="?attr/actionBarSize"
    app:theme="@style/ThemeOverlay.AppCompat.ActionBar">

    <com.astuetz.PagerSlidingTabStrip
        android:id="@+id/tabs"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
</android.support.v7.widget.Toolbar>
```

You can set the height you want to the toolbar and it will work. tested.
