### ISSUE TITLE
No view found for id 0x7f0b0061 (my.package.name:id/pager) for fragment

### ISSUE THREAD

**Issue by aniruddhasm** [jpardogo/PagerSlidingTabStrip#93]
Hello,

Thanks for the library.

I getting the below error when I switch from landscape to potrait or vice versa mode in view pager

"No view found for id 0x7f0b0061 (my.package.name:id/pager) for fragment"

04-12 00:29:14.779: E/AndroidRuntime(2042): FATAL EXCEPTION: main
04-12 00:29:14.779: E/AndroidRuntime(2042): Process: my.package.name, PID: 2042
04-12 00:29:14.779: E/AndroidRuntime(2042): java.lang.RuntimeException: Unable to start activity ComponentInfo{my.package.name/my.package.name.MainActivity}: 

java.lang.IllegalArgumentException: No view found for id 0x7f0b0061 (my.package.name:id/pager) for fragment HomeGridViewFragment{1edf92b5 #0 id=0x7f0b0061 

android:switcher:2131427425:1}
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3912)
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at android.app.ActivityThread.access$900(ActivityThread.java:144)
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at android.os.Looper.loop(Looper.java:135)
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at java.lang.reflect.Method.invoke(Native Method)
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at java.lang.reflect.Method.invoke(Method.java:372)
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
04-12 00:29:14.779: E/AndroidRuntime(2042): Caused by: java.lang.IllegalArgumentException: No view found for id 0x7f0b0061 (my.package.name:id/pager) for fragment 

HomeGridViewFragment{1edf92b5 #0 id=0x7f0b0061 android:switcher:2131427425:1}
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:939)
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1917)
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:544)
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at android.app.Activity.performStart(Activity.java:5949)
04-12 00:29:14.779: E/AndroidRuntime(2042): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)

Please help.
Thanks,

**Comment by jpardogo** [comment]
It is not library related
