### ISSUE TITLE
PagerSliding Strip fill parent and also make the tabs centered with slider bottom line to match width of device

### ISSUE THREAD

**Issue by divyanshunegi** [jpardogo/PagerSlidingTabStrip#94]
Hi,

I have two fragments named as "Created By Me" and "Invited By Others" now when i put this in the pageradapter the tabs are aligned to the left as they cant fill the complete width , I want so that is it possible the tabs divide the screen width as weight of 50% 50% and fill the width.

Thanks

**Comment by jpardogo** [comment]
Read the README file.
