### ISSUE TITLE
Bug when the indicator line, underline and dividers are drawn

### ISSUE THREAD

**Issue by jcdom** [jpardogo/PagerSlidingTabStrip#95]
I think there is an error when the indicator line, underline and dividers are drawn.
The order in which draw is wrong.

Current order:
1. Indicator line
2. Underline
3. Dividers

The problems are:
- The dividers are drew above the underline.
- The underline is drew above the indicator line, and indicator is not visible.

I consider correct this order:
1. Dividers
2. Underline
3. Indicator line

Pager configuration in activity_main.xml:
```xml
<com.astuetz.PagerSlidingTabStrip
        android:id="@+id/tabs"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        app:pstsUnderlineColor="#FF0000"
        app:pstsUnderlineHeight="6dp"
        app:pstsIndicatorHeight="6dp"
        app:pstsDividerWidth="6dp"
        app:pstsDividerColor="#0000FF"
        app:pstsTabPaddingLeftRight="10dp" />
```

- Current screenshot
![screenshot_2015-02-17-00-53-25](https://cloud.githubusercontent.com/assets/8142789/7144678/6d55bc02-e2e7-11e4-90b0-32f4b3418590.png)

- My pull request:
![screenshot_2015-02-17-00-54-12](https://cloud.githubusercontent.com/assets/8142789/7144798/157c19da-e2e8-11e4-9e20-b7a33bf3ba50.png)

**Comment by jpardogo** [comment]
Yeah that make sense

**Comment by jpardogo** [comment]
PR associate has been merged in dev branch for next release
